In [1]:
import numpy as np

In [2]:
dist=[24,56,97,100]
time=[.3,.7,.10,.28]

In [3]:
s=dist/time

TypeError: unsupported operand type(s) for /: 'list' and 'list'

In [4]:
np_dist=np.array(dist)
np_time=np.array(time)
print(np_dist,np_time)
speed=np_dist/np_time
print(speed)

[ 24  56  97 100] [0.3  0.7  0.1  0.28]
[ 80.          80.         970.         357.14285714]


In [8]:
print(type(speed))
print(speed[0])
print(speed[:2])
print(speed.shape)

<class 'numpy.ndarray'>
80.0
[80. 80.]
(4,)


In [9]:
#matrices
a=np.ones((3,5))
a

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [11]:
a=np.zeros((3,5))
a

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [12]:
a=np.full((3,5),12)
a

array([[12, 12, 12, 12, 12],
       [12, 12, 12, 12, 12],
       [12, 12, 12, 12, 12]])

In [17]:
a = np.array(4)
print("a:",a)
b = np.array([1, 2, 3, 4, 5])
print("b:",b)
c = np.array([[1, 2, 3], [4, 5, 6]])
print("c:",c)
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print("d:",d)


a: 4
b: [1 2 3 4 5]
c: [[1 2 3]
 [4 5 6]]
d: [[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [18]:
a=np.random.random((3,5))
a

array([[0.25449134, 0.4456585 , 0.69089043, 0.74153976, 0.85262823],
       [0.84074371, 0.12817375, 0.8887901 , 0.35628678, 0.80392367],
       [0.08968871, 0.79421261, 0.20045846, 0.82809044, 0.92111793]])

In [19]:
#1.Create a 3x3x3 array with random values
a=np.random.random((3,3,3))
a

array([[[0.73175807, 0.53328263, 0.07921868],
        [0.71837332, 0.89277617, 0.2525425 ],
        [0.41074564, 0.6311254 , 0.24052816]],

       [[0.44695561, 0.13457452, 0.96851715],
        [0.03933953, 0.73965846, 0.21170397],
        [0.06671403, 0.68890645, 0.97228582]],

       [[0.88889524, 0.93673165, 0.92883711],
        [0.85765535, 0.05402468, 0.12408853],
        [0.13939493, 0.90920567, 0.9512486 ]]])

In [20]:
#2.Create a 5x5 matrix with values 1,2,3,4 just below the diagonal
a=np.diag(np.arange(1,5),k=-1)
print(a)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [21]:
#3..Create a 8x8 matrix and fill it with a checkerboard pattern
a=np.zeros((8, 8), dtype=int)
a[1::2, ::2]=1
a[::2, 1::2]=1
print(a)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [23]:
#4.Normalize a 5x5 random matrix
a=np.random.random((5,5))
print("Before normalization:\n",a)
amax, amin = a.max(),a.min()
a=(a - amin)/(amax - amin)
print("After normalization:\n",a)

Before normalization:
 [[0.26968744 0.19049902 0.27220486 0.16172569 0.31321878]
 [0.27606475 0.26840082 0.74616439 0.06168488 0.31131921]
 [0.80824702 0.44886974 0.68720903 0.4553731  0.64952387]
 [0.43064703 0.53615138 0.88004815 0.11673904 0.00206993]
 [0.29174039 0.34574078 0.67552625 0.14493894 0.60795989]]
After normalization:
 [[0.30481111 0.21461704 0.30767839 0.18184478 0.35439245]
 [0.31207474 0.30334566 0.84750902 0.06790026 0.35222887]
 [0.91821992 0.50889623 0.78036001 0.51630343 0.73743736]
 [0.48814092 0.60830831 1.         0.13060587 0.        ]
 [0.32992898 0.39143436 0.76705355 0.162725   0.6900968 ]]


In [24]:
#5.common values between two arrays
a=np.array([1,2,4,3,5,6,7])
b=np.array([2,5,7])
print(np.intersect1d(a,b))

[2 5 7]


In [26]:
#6.How to get the dates of yesterday, today and tomorrow?
yesterday=np.datetime64('today','D')-np.timedelta64(1,'D')
print("Yestraday's Date:",yesterday)
today=np.datetime64('today','D')
print("Today's Date:",today)
tomorrow=np.datetime64('today','D')+np.timedelta64(1,'D')
print("Tomorrow's Date:",tomorrow)

Yestraday's Date: 2023-09-20
Today's Date: 2023-09-21
Tomorrow's Date: 2023-09-22


In [29]:
#7.check if two random array A and B are equal
A=np.random.random((3,3))
B=np.random.random((3,3))
equal = np.array_equal(A, B)
if equal:
    print("A and B are equal")
else:
    print("A and B are not equal")

A and B are not equal


In [30]:
#9.How to print all the values of an array?
a=np.arange(25)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]


In [33]:
a=np.random.rand(5,3)
np.set_printoptions(threshold = np.inf) 
print(a)

[[0.85884275 0.54672968 0.6177768 ]
 [0.24232974 0.69445805 0.02808114]
 [0.14940079 0.76089679 0.66700112]
 [0.52703731 0.46233692 0.93797916]
 [0.8339155  0.85807201 0.65164344]]


In [36]:
#10.Subtract the mean of each row of a matrix
a=np.array([[12,8,9],[7,6,5],[9,3,11]])
print("a:",a)
print("Subtract the mean of each row of matrix:\n")
result= a-a.mean(axis=1,keepdims=True)
print(result)


a: [[12  8  9]
 [ 7  6  5]
 [ 9  3 11]]
Subtract the mean of each row of matrix:

[[ 2.33333333 -1.66666667 -0.66666667]
 [ 1.          0.         -1.        ]
 [ 1.33333333 -4.66666667  3.33333333]]


In [41]:
#8.Create random vector of size 10 and replace the maximum value by 0
a= np.random.random(10)
print("a:\n",a)
a[a.argmax()]=0
print("Maximum value replaced by 0:\n",a)

a:
 [0.74381372 0.05339205 0.50690159 0.58717587 0.36683135 0.07379982
 0.83456804 0.25766523 0.72177563 0.18593586]
Maximum value replaced by 0:
 [0.74381372 0.05339205 0.50690159 0.58717587 0.36683135 0.07379982
 0.         0.25766523 0.72177563 0.18593586]


In [44]:
#12.How to get the diagonal of a dot product?
a=np.array([[2,4,6],[6,8,10],[2,3,5]])
b=np.array([[7,9,5],[4,3,5],[1,4,2]])
dotproduct=np.dot(a,b)
diagonal=np.diagonal(dotproduct)
print("Dot Product:\n",dotproduct)
print("\nDiagonal of Dot Product:",diagonal)

Dot Product:
 [[ 36  54  42]
 [ 84 118  90]
 [ 31  47  35]]

Diagonal of Dot Product: [ 36 118  35]


In [46]:
#13.How to find the most frequent value in an array?
a=np.random.randint(0,10,50)
print("Original array:\n",a)
print("Most frequent value in array:")
print(np.bincount(a).argmax())


Original array:
 [7 9 7 7 5 4 3 5 4 8 9 4 2 9 0 9 5 3 2 0 8 5 6 4 6 0 0 6 1 3 1 4 0 6 9 0 1
 0 5 5 3 2 4 6 5 4 2 7 4 1]
Most frequent value in array:
4


In [48]:
#14.How to get the n largest values of an array
import numpy as np
a=np.arange(12)
print("Original array:\n",a)
n=3
print("Largest values:",a[np.argsort(a)[-n:]])


Original array:
 [ 0  1  2  3  4  5  6  7  8  9 10 11]
Largest values: [ 9 10 11]


In [62]:
#15.How to create a record array from a regular array?
a=np.array([("Yasemin Rayner", 88.5, 90),
                 ("Ayaana Mcnamara", 87, 99),
             ("Jody Preece", 85.5, 91)])
print(a)
print("\nRecord array;")
result = np.rec.fromarrays(a.T,
                              names='col1, col2, col3')
print(result)

[['Yasemin Rayner' '88.5' '90']
 ['Ayaana Mcnamara' '87' '99']
 ['Jody Preece' '85.5' '91']]

Record array;
[('Yasemin Rayner', '88.5', '90') ('Ayaana Mcnamara', '87', '99')
 ('Jody Preece', '85.5', '91')]


In [63]:
regular_array = np.array([(1, 'Alice', 25),
                          (2, 'Bob', 30),
                          (3, 'Charlie', 35)],
                         dtype=[('ID', int), ('Name', 'U10'), ('Age', int)])
record_array = np.rec.fromarrays(regular_array.T, names='col1,col2,col3')

print("Regular Array:")
print(regular_array)

print("\nRecord Array:")
print(record_array)


Regular Array:
[(1, 'Alice', 25) (2, 'Bob', 30) (3, 'Charlie', 35)]

Record Array:
((1, 'Alice', 25), (2, 'Bob', 30), (3, 'Charlie', 35))


In [52]:
#16.swap two rows of array
a=np.array([[5,2,6], [8,7,0], [1,3,5], [9,4,1]])
print("a:\n",a)
a[[0,2]]=a[[2,0]]
print("after swapping:\n",a)

a:
 [[5 2 6]
 [8 7 0]
 [1 3 5]
 [9 4 1]]
after swapping:
 [[1 3 5]
 [8 7 0]
 [5 2 6]
 [9 4 1]]


In [53]:
a=np.array([[5,2,6], [8,7,0], [1,3,5], [9,4,1]])
print("a:\n",a)
a[[1,2]]=a[[2,1]]
print("after swapping:\n",a)

a:
 [[5 2 6]
 [8 7 0]
 [1 3 5]
 [9 4 1]]
after swapping:
 [[5 2 6]
 [1 3 5]
 [8 7 0]
 [9 4 1]]


In [54]:
#17.reshape to next dimension of numpy array
x=np.array([[23,34,121],[23,22,67],[686,434,123]])
x

array([[ 23,  34, 121],
       [ 23,  22,  67],
       [686, 434, 123]])

In [56]:
print(x.shape)
print(x.ndim)

(3, 3)
2


In [58]:
x=np.array([[23, 34, 121],[23, 22, 67],[686, 434, 123]])
reshaped_x = x.reshape(x.shape[0], x.shape[1], 1)
print("Original 2D Array:\n",x)
print("Reshaped 3D Array:\n",reshaped_x)

Original 2D Array:
 [[ 23  34 121]
 [ 23  22  67]
 [686 434 123]]
Reshaped 3D Array:
 [[[ 23]
  [ 34]
  [121]]

 [[ 23]
  [ 22]
  [ 67]]

 [[686]
  [434]
  [123]]]


In [59]:
print(reshaped_x.shape)
print(reshaped_x.ndim)

(3, 3, 1)
3


In [60]:
#11.vector,how to add 1 to each element indexed by a second vector
import numpy as np
given_vector = np.array([10, 20, 30, 40, 50])
indices_vector = np.array([1, 3, 1, 4, 2])
result_vector = np.zeros_like(given_vector)
np.add.at(result_vector, indices_vector, 1)
print("Given Vector:")
print(given_vector)

print("\nIndices Vector:")
print(indices_vector)

print("\nResult Vector:")
print(result_vector)


Given Vector:
[10 20 30 40 50]

Indices Vector:
[1 3 1 4 2]

Result Vector:
[0 2 1 1 1]


# MINI CASE STUDY 2

In [65]:
#dataset
np_olympic_country=np.array(['GBR','China','RUS','US','KOR','JPN','GER']) 
np_olympic_country_gold=np.array([29,38,24,46,13,7,11])
np_olympic_country_silver=np.array([17,28,25,28,8,14,11])
np_olympic_country_Bronze=np.array([19,22,32,29,7,17,14])

In [76]:
country=np_olympic_country
country

array(['GBR', 'China', 'RUS', 'US', 'KOR', 'JPN', 'GER'], dtype='<U5')

In [77]:
gold=np_olympic_country_gold
gold

array([29, 38, 24, 46, 13,  7, 11])

In [81]:
#country index with maximum gold
max_gold=np.argmax(gold)
max_gold

3

In [83]:
#country with maximum gold
country_with_max_gold=country[max_gold]
country_with_max_gold

'US'

In [87]:
#countries with more than 20 gold medals
goldmedals=gold>20
country_with_more_than_20goldmedals=country[goldmedals]
country_with_more_than_20goldmedals

array(['GBR', 'China', 'RUS', 'US'], dtype='<U5')

In [88]:
#each country with no of gold medals
for c,g in zip(country,gold):
    print(f"{c}: {g} gold medals")

GBR: 29 gold medals
China: 38 gold medals
RUS: 24 gold medals
US: 46 gold medals
KOR: 13 gold medals
JPN: 7 gold medals
GER: 11 gold medals


In [91]:
#each country name with total no of medals
silver=np_olympic_country_silver
silver

array([17, 28, 25, 28,  8, 14, 11])

In [92]:
bronze=np_olympic_country_Bronze
bronze

array([19, 22, 32, 29,  7, 17, 14])

In [94]:
total_medals=gold+silver+bronze
total_medals

array([ 65,  88,  81, 103,  28,  38,  36])

In [95]:
for c,g in zip(country,total_medals):
    print(f"{c}: {g} medals")

GBR: 65 medals
China: 88 medals
RUS: 81 medals
US: 103 medals
KOR: 28 medals
JPN: 38 medals
GER: 36 medals
